using Domain;
using Microsoft.AspNetCore.Identity;

namespace Persistence
{
    public class Seed
    {
        public static async Task SeedData(DataContext context, UserManager<AppUser> userManager)
        {
            if (!userManager.Users.Any() && !context.CleaningEvents.Any())
            {
                var users = new List<AppUser>
                {
                    new AppUser
                    {
                        DisplayName = "Shanaya Gangwani",
                        UserName = "shanaya",
                        Email = "shanaya@test.com"
                    },
                    new AppUser
                    {
                        DisplayName = "Meera Raj",
                        UserName = "meera",
                        Email = "meera@test.com"
                    },
                    new AppUser
                    {
                        DisplayName = "Raman Singh",
                        UserName = "raman",
                        Email = "raman@test.com"
                    }
                };

                foreach (var user in users)
                {
                    await userManager.CreateAsync(user, "Pa$$w0rd");
                    await userManager.AddToRoleAsync(user, "Member");
                }

                var admin = new AppUser { UserName = "admin", Email = "admin@test.com" };

                await userManager.CreateAsync(admin, "Pa$$w0rd");
                await userManager.AddToRolesAsync(admin, new[] { "Member", "Admin" });


                var cleaningEvents = new List<CleaningEvent>
                {
                    new CleaningEvent
                    {
                        Title = "Beach Cleaning at Vasco",
                        Date = DateTime.UtcNow.AddMonths(-2),
                        Description = "Cleaning Event",
                        Category = "Beach Cleaning",
                        City = "Vasco da Gama",
                        Venue = "Velsao Beach",
                        Attendees = new List<CleaningEventAttendee>
                        {
                            new CleaningEventAttendee { AppUser = users[0], IsHost = true }
                        }
                    },
                    new CleaningEvent
                    {
                        Title = "Let's make India's Capital City clean",
                        Date = DateTime.UtcNow.AddMonths(-1),
                        Description = "Cleaning Event 1 month ago",
                        Category = "City Cleaning",
                        City = "New Delhi",
                        Venue = "Connaught Place",
                        Attendees = new List<CleaningEventAttendee>
                        {
                            new CleaningEventAttendee { AppUser = users[0], IsHost = true },
                            new CleaningEventAttendee { AppUser = users[1], IsHost = false },
                        }
                    },
                    new CleaningEvent
                    {
                        Title = "Let's clean  India Silicon Valley",
                        Date = DateTime.UtcNow.AddMonths(1),
                        Description = "Cleaning Event",
                        Category = "Educational Event",
                        City = "Bangalore",
                        Venue = "Koramangala",
                        Attendees = new List<CleaningEventAttendee>
                        {
                            new CleaningEventAttendee { AppUser = users[2], IsHost = true },
                            new CleaningEventAttendee { AppUser = users[1], IsHost = false },
                        }
                    },
                    new CleaningEvent
                    {
                        Title = "Orange City Cleanliness Campaign",
                        Date = DateTime.UtcNow.AddMonths(2),
                        Description = "Cleaning Event",
                        Category = "College campus cleaning",
                        City = "Nagpur",
                        Venue = "Bardi",
                        Attendees = new List<CleaningEventAttendee>
                        {
                            new CleaningEventAttendee { AppUser = users[0], IsHost = true },
                            new CleaningEventAttendee { AppUser = users[2], IsHost = false },
                        }
                    },
                    new CleaningEvent
                    {
                        Title = "Let's clean Nizams city",
                        Date = DateTime.UtcNow.AddMonths(3),
                        Description = "Cleaning Event",
                        Category = "City Cleaning",
                        City = "Hyderabad",
                        Venue = "Nizampet",
                        Attendees = new List<CleaningEventAttendee>
                        {
                            new CleaningEventAttendee { AppUser = users[1], IsHost = true },
                            new CleaningEventAttendee { AppUser = users[0], IsHost = false },
                        }
                    },
                    new CleaningEvent
                    {
                        Title = "Go Goa Clean",
                        Date = DateTime.UtcNow.AddMonths(4),
                        Description = "Cleaning Event",
                        Category = "Beach Cleaning",
                        City = "Panaji",
                        Venue = "Odxel Beach",
                        Attendees = new List<CleaningEventAttendee>
                        {
                            new CleaningEventAttendee { AppUser = users[1], IsHost = true }
                        }
                    },
                    new CleaningEvent
                    {
                        Title = "Clean IITs clean India",
                        Date = DateTime.UtcNow.AddMonths(5),
                        Description = "Cleaning event",
                        Category = "College Campus Cleaning ",
                        City = "New Delhi",
                        Venue = "IIT Delhi",
                        Attendees = new List<CleaningEventAttendee>
                        {
                            new CleaningEventAttendee { AppUser = users[0], IsHost = true },
                            new CleaningEventAttendee { AppUser = users[1], IsHost = false },
                        }
                    },
                    new CleaningEvent
                    {
                        Title = "Know more about Swachhata",
                        Date = DateTime.UtcNow.AddMonths(6),
                        Description = "Cleaning Event",
                        Category = "Educational Event",
                        City = "Bhopal",
                        Venue = "Habib Ganj ",
                        Attendees = new List<CleaningEventAttendee>
                        {
                            new CleaningEventAttendee { AppUser = users[2], IsHost = true },
                            new CleaningEventAttendee { AppUser = users[1], IsHost = false },
                        }
                    },
                    new CleaningEvent
                    {
                        Title = "Clean Bihar Campaign",
                        Date = DateTime.UtcNow.AddMonths(7),
                        Description = "Lets make Bihar's capital clean",
                        Category = "City Cleaning",
                        City = "Patna",
                        Venue = "Mithapur",
                        Attendees = new List<CleaningEventAttendee>
                        {
                            new CleaningEventAttendee { AppUser = users[0], IsHost = true },
                            new CleaningEventAttendee { AppUser = users[2], IsHost = false },
                        }
                    },
                    new CleaningEvent
                    {
                        Title = "Clean Mangalore Campaign",
                        Date = DateTime.UtcNow.AddMonths(8),
                        Description = "Cleaning Event to support Swacch Bharat",
                        Category = "Beach Cleaning",
                        City = "Mangalore",
                        Venue = "Mulki Beach",
                        Attendees = new List<CleaningEventAttendee>
                        {
                            new CleaningEventAttendee { AppUser = users[2], IsHost = true },
                            new CleaningEventAttendee { AppUser = users[1], IsHost = false },
                        }
                    }
                };

                await context.CleaningEvents.AddRangeAsync(cleaningEvents);
                await context.SaveChangesAsync();
            }

            if (context.Complaints.Any())
                return;

            var complaints = new List<Complaint>
            {
                new Complaint
                {
                    ComplaintType = "SEWAGE",
                    ComplaintSubType = "REPAIRING",
                    DescriptionofComplaint =
                        "The sewage pipes are damaged and the dirty water is coming on roads",
                    ComplaintLocationHouseNo = "11",
                    ComplaintLocationHouseName = "Shanti Niwas",
                    ComplaintLocationAreaInAddress = "Gauthana",
                    ComplaintLocationZoneWardNo = "D2",
                    ComplaintLocationArea1 = "Gauthana",
                    ComplaintLocationArea2 = "Gauthana",
                    ComplaintLocationCity = "AALOT NAGAR PARISHAD  / आलोट नगर परिषद",
                    ComplaintLocationPincode = "460001",
                    ComplainantName = "Aman Jindal",
                    ComplainantAddressWard = "WARD 1",
                    ComplainantAddressHouseNo = "11",
                    ComplainantAddressHouseName = "Shanti Niwas",
                    ComplainantAddressAreaInAddress = "Gauthana",
                    ComplainantAddressZoneWardNo = "D2",
                    ComplainantAddressArea1 = "Gauthana",
                    ComplainantAddressArea2 = "Gauthana",
                    ComplainantAddressLandmark = "Durga Devi Temple",
                    ComplainantAddressCity = "AALOT NAGAR PARISHAD  / आलोट नगर परिषद",
                    ComplainantAddressState = "Madhya Pradesh",
                    ComplainantAddressCountry = "India",
                    ComplainantAddressSTDCodeOfficeTelephone = "+912",
                    ComplainantAddressOfficeTelephone = "6285483819",
                    ComplainantAddressSTDCodeResidenceTelephone = "+912",
                    ComplainantAddressResidenceTelephone = "8595004794",
                    PhoneNumber = "0890055565",
                    Email = "amanjindal@gmail.com",
                    PhotoUrl =
                        "https://res.cloudinary.com/sneha09/image/upload/v1681061451/csjktq34pwysj8vviz1n.png",
                    ComplaintStatus = "In Review"
                },
                new Complaint
                {
                    ComplaintType = "GARBAGE COLLECTION",
                    ComplaintSubType = "DELAY IN GARBAGE COLLECTION",
                    DescriptionofComplaint =
                        "There's no garbage collection from past 1 week and bins are overflowing, dogs are taking out the garbage and spreading on all over the streets",
                    ComplaintLocationHouseNo = "15",
                    ComplaintLocationHouseName = "Liana House",
                    ComplaintLocationAreaInAddress = "Tikari",
                    ComplaintLocationZoneWardNo = "D10",
                    ComplaintLocationArea1 = "Tikari",
                    ComplaintLocationArea2 = "Tikari",
                    ComplaintLocationCity = "CHICHOLI NAGAR PARISHAD / चिचोली नगर परिषद्",
                    ComplaintLocationPincode = "460001",
                    ComplainantName = "Aarav Kumar",
                    ComplainantAddressWard = "WARD 5",
                    ComplainantAddressHouseNo = "15",
                    ComplainantAddressHouseName = "Liana House",
                    ComplainantAddressAreaInAddress = "Tikari",
                    ComplainantAddressZoneWardNo = "D10",
                    ComplainantAddressArea1 = "Tikari",
                    ComplainantAddressArea2 = "Tikari",
                    ComplainantAddressLandmark = "ELC Church",
                    ComplainantAddressCity = "CHICHOLI NAGAR PARISHAD / चिचोली नगर परिषद्",
                    ComplainantAddressState = "Madhya Pradesh",
                    ComplainantAddressCountry = "India",
                    ComplainantAddressSTDCodeOfficeTelephone = "+912",
                    ComplainantAddressOfficeTelephone = "8127114938",
                    ComplainantAddressSTDCodeResidenceTelephone = "+912",
                    ComplainantAddressResidenceTelephone = "0244478581",
                    PhoneNumber = "4897388306",
                    Email = "aaravkumar@gmail.com",
                    PhotoUrl =
                        "https://res.cloudinary.com/sneha09/image/upload/v1682692665/celalnin2_sgvwfx.png",
                    ComplaintStatus = "Resolved"
                },
                new Complaint
                {
                    ComplaintType = "SEWAGE",
                    ComplaintSubType = "REPAIRING",
                    DescriptionofComplaint =
                        "The sewage pipes are damaged from past 1 week and the dirty water is coming on roads and causing Diseases like Malaria",
                    ComplaintLocationHouseNo = "12",
                    ComplaintLocationHouseName = "Durga Niwas",
                    ComplaintLocationAreaInAddress = "Sadar",
                    ComplaintLocationZoneWardNo = "D3",
                    ComplaintLocationArea1 = "Sadar",
                    ComplaintLocationArea2 = "Sadar",
                    ComplaintLocationCity = "Khandwa Municipal Corporation",
                    ComplaintLocationPincode = "460001",
                    ComplainantName = "Amisha Gangwani",
                    ComplainantAddressWard = "WARD 2",
                    ComplainantAddressHouseNo = "12",
                    ComplainantAddressHouseName = "Durga Niwas",
                    ComplainantAddressAreaInAddress = "Sadar",
                    ComplainantAddressZoneWardNo = "D3",
                    ComplainantAddressArea1 = "Sadar",
                    ComplainantAddressArea2 = "Sadar",
                    ComplainantAddressLandmark = "Samsung Showroom",
                    ComplainantAddressCity = "Khandwa Municipal Corporation",
                    ComplainantAddressState = "Madhya Pradesh",
                    ComplainantAddressCountry = "India",
                    ComplainantAddressSTDCodeOfficeTelephone = "+912",
                    ComplainantAddressOfficeTelephone = "6361935853",
                    ComplainantAddressSTDCodeResidenceTelephone = "+912",
                    ComplainantAddressResidenceTelephone = "0119347100",
                    PhoneNumber = "0191932396",
                    Email = "amishagangwani@gmail.com",
                    PhotoUrl =
                        "https://res.cloudinary.com/sneha09/image/upload/v1682692665/cleain_eqbwwm.png",
                    ComplaintStatus = "Filed"
                },
                new Complaint
                {
                    ComplaintType = "SEWAGE",
                    ComplaintSubType = "REPAIRING",
                    DescriptionofComplaint =
                        "The sewage pipes are damaged from past 1 week and the dirty water is coming on roads and causing Diseases like Malaria",
                    ComplaintLocationHouseNo = "88",
                    ComplaintLocationHouseName = "Durga Niwas",
                    ComplaintLocationAreaInAddress = "Jamnagar market",
                    ComplaintLocationZoneWardNo = "D10",
                    ComplaintLocationArea1 = "Jamnagar market",
                    ComplaintLocationArea2 = "Jamnagar market",
                    ComplaintLocationCity = "Kolhapur Municipal Corporation",
                    ComplaintLocationPincode = "460001",
                    ComplainantName = "Prabhat KP",
                    ComplainantAddressWard = "WARD 8",
                    ComplainantAddressHouseNo = "20",
                    ComplainantAddressHouseName = "Durga Niwas",
                    ComplainantAddressAreaInAddress = "Jamnagar market",
                    ComplainantAddressZoneWardNo = "D10",
                    ComplainantAddressArea1 = "Jamnagar market",
                    ComplainantAddressArea2 = "Jamnagar market",
                    ComplainantAddressLandmark = "Samsung Showroom",
                    ComplainantAddressCity = "Kolhapur Municipal Corporation",
                    ComplainantAddressState = "Maharashtra",
                    ComplainantAddressCountry = "India",
                    ComplainantAddressSTDCodeOfficeTelephone = "020",
                    ComplainantAddressOfficeTelephone = "0397746135",
                    ComplainantAddressSTDCodeResidenceTelephone = "020",
                    ComplainantAddressResidenceTelephone = "1437003314",
                    PhoneNumber = "3789990358",
                    Email = "prabhatkp@gmail.com",
                    PhotoUrl =
                        "https://res.cloudinary.com/sneha09/image/upload/v1682692665/cleain_eqbwwm.png",
                    ComplaintStatus = "In Review"
                },
                new Complaint
                {
                    ComplaintType = "SEWAGE",
                    ComplaintSubType = "REPAIRING",
                    DescriptionofComplaint =
                        "The sewage pipes are damaged from past 1 week and the dirty water is coming on roads and causing Diseases like Malaria",
                    ComplaintLocationHouseNo = "12",
                    ComplaintLocationHouseName = "Durga Niwas",
                    ComplaintLocationAreaInAddress = "Sadar",
                    ComplaintLocationZoneWardNo = "D3",
                    ComplaintLocationArea1 = "Sadar",
                    ComplaintLocationArea2 = "Sadar",
                    ComplaintLocationCity = "Aurangabad Municipal Corporation",
                    ComplaintLocationPincode = "460001",
                    ComplainantName = "Himani Sinha",
                    ComplainantAddressWard = "WARD 2",
                    ComplainantAddressHouseNo = "12",
                    ComplainantAddressHouseName = "Durga Niwas",
                    ComplainantAddressAreaInAddress = "Sadar",
                    ComplainantAddressZoneWardNo = "D3",
                    ComplainantAddressArea1 = "Sadar",
                    ComplainantAddressArea2 = "Sadar",
                    ComplainantAddressLandmark = "Samsung Showroom",
                    ComplainantAddressCity = "Aurangabad Municipal Corporation",
                    ComplainantAddressState = "Maharashtra",
                    ComplainantAddressCountry = "India",
                    ComplainantAddressSTDCodeOfficeTelephone = "020",
                    ComplainantAddressOfficeTelephone = "6177580486",
                    ComplainantAddressSTDCodeResidenceTelephone = "020",
                    ComplainantAddressResidenceTelephone = "4880411973",
                    PhoneNumber = "8933933204",
                    Email = "himanisinha@gmail.com",
                    PhotoUrl =
                        "https://res.cloudinary.com/sneha09/image/upload/v1682692665/cleain_eqbwwm.png",
                    ComplaintStatus = "Resolved"
                },
                new Complaint
                {
                    ComplaintType = "SEWAGE",
                    ComplaintSubType = "REPAIRING",
                    DescriptionofComplaint =
                        "The sewage pipes are damaged from past 1 week and the dirty water is coming on roads and causing Diseases like Malaria",
                    ComplaintLocationHouseNo = "12",
                    ComplaintLocationHouseName = "Durga Niwas",
                    ComplaintLocationAreaInAddress = "Sadar",
                    ComplaintLocationZoneWardNo = "D3",
                    ComplaintLocationArea1 = "Sadar",
                    ComplaintLocationArea2 = "Sadar",
                    ComplaintLocationCity = "Vasai-Virar Municipal Corporation",
                    ComplaintLocationPincode = "460001",
                    ComplainantName = "Kavita Phogat",
                    ComplainantAddressWard = "WARD 2",
                    ComplainantAddressHouseNo = "12",
                    ComplainantAddressHouseName = "Durga Niwas",
                    ComplainantAddressAreaInAddress = "Sadar",
                    ComplainantAddressZoneWardNo = "D3",
                    ComplainantAddressArea1 = "Sadar",
                    ComplainantAddressArea2 = "Sadar",
                    ComplainantAddressLandmark = "Samsung Showroom",
                    ComplainantAddressCity = "Vasai-Virar Municipal Corporation",
                    ComplainantAddressState = "Maharashtra",
                    ComplainantAddressCountry = "India",
                    ComplainantAddressSTDCodeOfficeTelephone = "020",
                    ComplainantAddressOfficeTelephone = "9719403501",
                    ComplainantAddressSTDCodeResidenceTelephone = "020",
                    ComplainantAddressResidenceTelephone = "4930196675",
                    PhoneNumber = "9517266949",
                    Email = "kavitaphogat@gmail.com",
                    PhotoUrl =
                        "https://res.cloudinary.com/sneha09/image/upload/v1682692665/cleain_eqbwwm.png",
                    ComplaintStatus = "Resolved"
                },
                new Complaint
                {
                    ComplaintType = "SEWAGE",
                    ComplaintSubType = "REPAIRING",
                    DescriptionofComplaint =
                        "The sewage pipes are damaged from past 1 week and the dirty water is coming on roads and causing Diseases like Malaria",
                    ComplaintLocationHouseNo = "12",
                    ComplaintLocationHouseName = "Durga Niwas",
                    ComplaintLocationAreaInAddress = "Sadar",
                    ComplaintLocationZoneWardNo = "D3",
                    ComplaintLocationArea1 = "Sadar",
                    ComplaintLocationArea2 = "Sadar",
                    ComplaintLocationCity = "Kalyan-Dombivli Municipal Corporation",
                    ComplaintLocationPincode = "460001",
                    ComplainantName = "Kavya T",
                    ComplainantAddressWard = "WARD 2",
                    ComplainantAddressHouseNo = "12",
                    ComplainantAddressHouseName = "Durga Niwas",
                    ComplainantAddressAreaInAddress = "Sadar",
                    ComplainantAddressZoneWardNo = "D3",
                    ComplainantAddressArea1 = "Sadar",
                    ComplainantAddressArea2 = "Sadar",
                    ComplainantAddressLandmark = "Samsung Showroom",
                    ComplainantAddressCity = "Kalyan-Dombivli Municipal Corporation",
                    ComplainantAddressState = "Maharashtra",
                    ComplainantAddressCountry = "India",
                    ComplainantAddressSTDCodeOfficeTelephone = "020",
                    ComplainantAddressOfficeTelephone = "7383680751",
                    ComplainantAddressSTDCodeResidenceTelephone = "020",
                    ComplainantAddressResidenceTelephone = "6824274508",
                    PhoneNumber = "5341811614",
                    Email = "kavyakool@gmail.com",
                    PhotoUrl =
                        "https://res.cloudinary.com/sneha09/image/upload/v1682692665/cleain_eqbwwm.png",
                    ComplaintStatus = "Filed"
                },
                new Complaint
                {
                    ComplaintType = "SEWAGE",
                    ComplaintSubType = "REPAIRING",
                    DescriptionofComplaint =
                        "The sewage pipes are damaged from past 1 week and the dirty water is coming on roads and causing Diseases like Malaria",
                    ComplaintLocationHouseNo = "12",
                    ComplaintLocationHouseName = "Durga Niwas",
                    ComplaintLocationAreaInAddress = "Sadar",
                    ComplaintLocationZoneWardNo = "D3",
                    ComplaintLocationArea1 = "Sadar",
                    ComplaintLocationArea2 = "Sadar",
                    ComplaintLocationCity = "Siliguri Municipal Corporation",
                    ComplaintLocationPincode = "460001",
                    ComplainantName = "Teertha Singh",
                    ComplainantAddressWard = "WARD 2",
                    ComplainantAddressHouseNo = "12",
                    ComplainantAddressHouseName = "Durga Niwas",
                    ComplainantAddressAreaInAddress = "Sadar",
                    ComplainantAddressZoneWardNo = "D3",
                    ComplainantAddressArea1 = "Sadar",
                    ComplainantAddressArea2 = "Sadar",
                    ComplainantAddressLandmark = "Samsung Showroom",
                    ComplainantAddressCity = "Siliguri Municipal Corporation",
                    ComplainantAddressState = "West Bengal",
                    ComplainantAddressCountry = "India",
                    ComplainantAddressSTDCodeOfficeTelephone = "033",
                    ComplainantAddressOfficeTelephone = "6506811526",
                    ComplainantAddressSTDCodeResidenceTelephone = "033",
                    ComplainantAddressResidenceTelephone = "4958410438",
                    PhoneNumber = "6452328068",
                    Email = "teerthateer@gmail.com",
                    PhotoUrl =
                        "https://res.cloudinary.com/sneha09/image/upload/v1682692665/cleain_eqbwwm.png",
                    ComplaintStatus = "In Review"
                },
                new Complaint
                {
                    ComplaintType = "SEWAGE",
                    ComplaintSubType = "REPAIRING",
                    DescriptionofComplaint =
                        "The sewage pipes are damaged from past 1 week and the dirty water is coming on roads and causing Diseases like Malaria",
                    ComplaintLocationHouseNo = "12",
                    ComplaintLocationHouseName = "Durga Niwas",
                    ComplaintLocationAreaInAddress = "Sadar",
                    ComplaintLocationZoneWardNo = "D3",
                    ComplaintLocationArea1 = "Sadar",
                    ComplaintLocationArea2 = "Sadar",
                    ComplaintLocationCity = "North Delhi Municipal Corporation (NDMC)",
                    ComplaintLocationPincode = "460001",
                    ComplainantName = "Pooja Sharma",
                    ComplainantAddressWard = "WARD 2",
                    ComplainantAddressHouseNo = "12",
                    ComplainantAddressHouseName = "Durga Niwas",
                    ComplainantAddressAreaInAddress = "Sadar",
                    ComplainantAddressZoneWardNo = "D3",
                    ComplainantAddressArea1 = "Sadar",
                    ComplainantAddressArea2 = "Sadar",
                    ComplainantAddressLandmark = "Samsung Showroom",
                    ComplainantAddressCity = "North Delhi Municipal Corporation (NDMC)",
                    ComplainantAddressState = "New Delhi",
                    ComplainantAddressCountry = "India",
                    ComplainantAddressSTDCodeOfficeTelephone = "011",
                    ComplainantAddressOfficeTelephone = "6460373601",
                    ComplainantAddressSTDCodeResidenceTelephone = "011",
                    ComplainantAddressResidenceTelephone = "6990119525",
                    PhoneNumber = "6567701923",
                    Email = "sharmapooja@gmail.com",
                    PhotoUrl =
                        "https://res.cloudinary.com/sneha09/image/upload/v1682692665/cleain_eqbwwm.png",
                    ComplaintStatus = "In Review"
                },
                new Complaint
                {
                    ComplaintType = "SEWAGE",
                    ComplaintSubType = "REPAIRING",
                    DescriptionofComplaint =
                        "The sewage pipes are damaged from past 1 week and the dirty water is coming on roads and causing Diseases like Malaria",
                    ComplaintLocationHouseNo = "12",
                    ComplaintLocationHouseName = "Durga Niwas",
                    ComplaintLocationAreaInAddress = "Sadar",
                    ComplaintLocationZoneWardNo = "D3",
                    ComplaintLocationArea1 = "Sadar",
                    ComplaintLocationArea2 = "Sadar",
                    ComplaintLocationCity = "East Delhi Municipal Corporation (EDMC)",
                    ComplaintLocationPincode = "460001",
                    ComplainantName = "Seeta Devi",
                    ComplainantAddressWard = "WARD 2",
                    ComplainantAddressHouseNo = "12",
                    ComplainantAddressHouseName = "Durga Niwas",
                    ComplainantAddressAreaInAddress = "Sadar",
                    ComplainantAddressZoneWardNo = "D3",
                    ComplainantAddressArea1 = "Sadar",
                    ComplainantAddressArea2 = "Sadar",
                    ComplainantAddressLandmark = "Samsung Showroom",
                    ComplainantAddressCity = "East Delhi Municipal Corporation (EDMC)",
                    ComplainantAddressState = "New Delhi",
                    ComplainantAddressCountry = "India",
                    ComplainantAddressSTDCodeOfficeTelephone = "011",
                    ComplainantAddressOfficeTelephone = "4178483972",
                    ComplainantAddressSTDCodeResidenceTelephone = "011",
                    ComplainantAddressResidenceTelephone = "9086434333",
                    PhoneNumber = "9529639106",
                    Email = "seetadevi@gmail.com",
                    PhotoUrl =
                        "https://res.cloudinary.com/sneha09/image/upload/v1682692665/cleain_eqbwwm.png",
                    ComplaintStatus = "Resolved"
                },
                new Complaint
                {
                    ComplaintType = "SEWAGE",
                    ComplaintSubType = "REPAIRING",
                    DescriptionofComplaint =
                        "The sewage pipes are damaged from past 1 week and the dirty water is coming on roads and causing Diseases like Malaria",
                    ComplaintLocationHouseNo = "12",
                    ComplaintLocationHouseName = "Durga Niwas",
                    ComplaintLocationAreaInAddress = "Sadar",
                    ComplaintLocationZoneWardNo = "D3",
                    ComplaintLocationArea1 = "Sadar",
                    ComplaintLocationArea2 = "Sadar",
                    ComplaintLocationCity = "East Delhi Municipal Corporation (EDMC)",
                    ComplaintLocationPincode = "460001",
                    ComplainantName = "Samiksha Tarpade",
                    ComplainantAddressWard = "WARD 2",
                    ComplainantAddressHouseNo = "12",
                    ComplainantAddressHouseName = "Durga Niwas",
                    ComplainantAddressAreaInAddress = "Sadar",
                    ComplainantAddressZoneWardNo = "D3",
                    ComplainantAddressArea1 = "Sadar",
                    ComplainantAddressArea2 = "Sadar",
                    ComplainantAddressLandmark = "Samsung Showroom",
                    ComplainantAddressCity = "East Delhi Municipal Corporation (EDMC)",
                    ComplainantAddressState = "New Delhi",
                    ComplainantAddressCountry = "India",
                    ComplainantAddressSTDCodeOfficeTelephone = "011",
                    ComplainantAddressOfficeTelephone = "4381133940",
                    ComplainantAddressSTDCodeResidenceTelephone = "011",
                    ComplainantAddressResidenceTelephone = "1012366696",
                    PhoneNumber = "0766282054",
                    Email = "samikshatarpade@gmail.com",
                    PhotoUrl =
                        "https://res.cloudinary.com/sneha09/image/upload/v1682692665/cleain_eqbwwm.png",
                    ComplaintStatus = "Filed"
                },
                new Complaint
                {
                    ComplaintType = "SEWAGE",
                    ComplaintSubType = "REPAIRING",
                    DescriptionofComplaint =
                        "The sewage pipes are damaged from past 1 week and the dirty water is coming on roads and causing Diseases like Malaria",
                    ComplaintLocationHouseNo = "12",
                    ComplaintLocationHouseName = "Durga Niwas",
                    ComplaintLocationAreaInAddress = "Sadar",
                    ComplaintLocationZoneWardNo = "D3",
                    ComplaintLocationArea1 = "Sadar",
                    ComplaintLocationArea2 = "Sadar",
                    ComplaintLocationCity = "Dewas Municipal Corporation.",
                    ComplaintLocationPincode = "460001",
                    ComplainantName = "Lavanya GP",
                    ComplainantAddressWard = "WARD 2",
                    ComplainantAddressHouseNo = "12",
                    ComplainantAddressHouseName = "Durga Niwas",
                    ComplainantAddressAreaInAddress = "Sadar",
                    ComplainantAddressZoneWardNo = "D3",
                    ComplainantAddressArea1 = "Sadar",
                    ComplainantAddressArea2 = "Sadar",
                    ComplainantAddressLandmark = "Samsung Showroom",
                    ComplainantAddressCity = "Dewas Municipal Corporation.",
                    ComplainantAddressState = "Madhya Pradesh",
                    ComplainantAddressCountry = "India",
                    ComplainantAddressSTDCodeOfficeTelephone = "+912",
                    ComplainantAddressOfficeTelephone = "9008558639",
                    ComplainantAddressSTDCodeResidenceTelephone = "+912",
                    ComplainantAddressResidenceTelephone = "8658704669",
                    PhoneNumber = "4590597443",
                    Email = "gplavanya@gmail.com",
                    PhotoUrl =
                        "https://res.cloudinary.com/sneha09/image/upload/v1682692665/cleain_eqbwwm.png",
                    ComplaintStatus = "Filed"
                },
                new Complaint
                {
                    ComplaintType = "SEWAGE",
                    ComplaintSubType = "REPAIRING",
                    DescriptionofComplaint =
                        "The sewage pipes are damaged from past 1 week and the dirty water is coming on roads and causing Diseases like Malaria",
                    ComplaintLocationHouseNo = "12",
                    ComplaintLocationHouseName = "Durga Niwas",
                    ComplaintLocationAreaInAddress = "Sadar",
                    ComplaintLocationZoneWardNo = "D3",
                    ComplaintLocationArea1 = "Sadar",
                    ComplaintLocationArea2 = "Sadar",
                    ComplaintLocationCity = "Bhopal Municipal Corporation",
                    ComplaintLocationPincode = "460001",
                    ComplainantName = "Ankush Singh",
                    ComplainantAddressWard = "WARD 2",
                    ComplainantAddressHouseNo = "12",
                    ComplainantAddressHouseName = "Durga Niwas",
                    ComplainantAddressAreaInAddress = "Sadar",
                    ComplainantAddressZoneWardNo = "D3",
                    ComplainantAddressArea1 = "Sadar",
                    ComplainantAddressArea2 = "Sadar",
                    ComplainantAddressLandmark = "Samsung Showroom",
                    ComplainantAddressCity = "Bhopal Municipal Corporation",
                    ComplainantAddressState = "Madhya Pradesh",
                    ComplainantAddressCountry = "India",
                    ComplainantAddressSTDCodeOfficeTelephone = "+912",
                    ComplainantAddressOfficeTelephone = "3170385198",
                    ComplainantAddressSTDCodeResidenceTelephone = "+912",
                    ComplainantAddressResidenceTelephone = "8244810423",
                    PhoneNumber = "6708732661",
                    Email = "ankuusingh@gmail.com",
                    PhotoUrl =
                        "https://res.cloudinary.com/sneha09/image/upload/v1682692665/cleain_eqbwwm.png",
                    ComplaintStatus = "In Review"
                },
                new Complaint
                {
                    ComplaintType = "SEWAGE",
                    ComplaintSubType = "REPAIRING",
                    DescriptionofComplaint =
                        "The sewage pipes are damaged from past 1 week and the dirty water is coming on roads and causing Diseases like Malaria",
                    ComplaintLocationHouseNo = "12",
                    ComplaintLocationHouseName = "Durga Niwas",
                    ComplaintLocationAreaInAddress = "Sadar",
                    ComplaintLocationZoneWardNo = "D3",
                    ComplaintLocationArea1 = "Sadar",
                    ComplaintLocationArea2 = "Sadar",
                    ComplaintLocationCity = "Chhindwara Municipal Corporation",
                    ComplaintLocationPincode = "460001",
                    ComplainantName = "Ankit Upadhaya",
                    ComplainantAddressWard = "WARD 2",
                    ComplainantAddressHouseNo = "12",
                    ComplainantAddressHouseName = "Durga Niwas",
                    ComplainantAddressAreaInAddress = "Sadar",
                    ComplainantAddressZoneWardNo = "D3",
                    ComplainantAddressArea1 = "Sadar",
                    ComplainantAddressArea2 = "Sadar",
                    ComplainantAddressLandmark = "Samsung Showroom",
                    ComplainantAddressCity = "Chhindwara Municipal Corporation",
                    ComplainantAddressState = "Madhya Pradesh",
                    ComplainantAddressCountry = "India",
                    ComplainantAddressSTDCodeOfficeTelephone = "+912",
                    ComplainantAddressOfficeTelephone = "1002867628",
                    ComplainantAddressSTDCodeResidenceTelephone = "+912",
                    ComplainantAddressResidenceTelephone = "4337106632",
                    PhoneNumber = "5273506994",
                    Email = "amishagangwani@gmail.com",
                    PhotoUrl =
                        "https://res.cloudinary.com/sneha09/image/upload/v1682692665/cleain_eqbwwm.png",
                    ComplaintStatus = "Filed"
                },
                new Complaint
                {
                    ComplaintType = "SEWAGE",
                    ComplaintSubType = "REPAIRING",
                    DescriptionofComplaint =
                        "The sewage pipes are damaged from past 1 week and the dirty water is coming on roads and causing Diseases like Malaria",
                    ComplaintLocationHouseNo = "12",
                    ComplaintLocationHouseName = "Durga Niwas",
                    ComplaintLocationAreaInAddress = "Sadar",
                    ComplaintLocationZoneWardNo = "D3",
                    ComplaintLocationArea1 = "Sadar",
                    ComplaintLocationArea2 = "Sadar",
                    ComplaintLocationCity = "Kolkata Municipal Corporation",
                    ComplaintLocationPincode = "460001",
                    ComplainantName = "Prashant Dubey",
                    ComplainantAddressWard = "WARD 2",
                    ComplainantAddressHouseNo = "12",
                    ComplainantAddressHouseName = "Durga Niwas",
                    ComplainantAddressAreaInAddress = "Sadar",
                    ComplainantAddressZoneWardNo = "D3",
                    ComplainantAddressArea1 = "Sadar",
                    ComplainantAddressArea2 = "Sadar",
                    ComplainantAddressLandmark = "Samsung Showroom",
                    ComplainantAddressCity = "Kolkata Municipal Corporation",
                    ComplainantAddressState = "West Bengal",
                    ComplainantAddressCountry = "India",
                    ComplainantAddressSTDCodeOfficeTelephone = "033",
                    ComplainantAddressOfficeTelephone = "3083423189",
                    ComplainantAddressSTDCodeResidenceTelephone = "033",
                    ComplainantAddressResidenceTelephone = "0912530631",
                    PhoneNumber = "5709377636",
                    Email = "prashantdubey@gmail.com",
                    PhotoUrl =
                        "https://res.cloudinary.com/sneha09/image/upload/v1682692665/cleain_eqbwwm.png",
                    ComplaintStatus = "Filed"
                },
                new Complaint
                {
                    ComplaintType = "SEWAGE",
                    ComplaintSubType = "REPAIRING",
                    DescriptionofComplaint =
                        "The sewage pipes are damaged from past 1 week and the dirty water is coming on roads and causing Diseases like Malaria",
                    ComplaintLocationHouseNo = "12",
                    ComplaintLocationHouseName = "Durga Niwas",
                    ComplaintLocationAreaInAddress = "Sadar",
                    ComplaintLocationZoneWardNo = "D3",
                    ComplaintLocationArea1 = "Sadar",
                    ComplaintLocationArea2 = "Sadar",
                    ComplaintLocationCity = "Howrah Municipal Corporation",
                    ComplaintLocationPincode = "460001",
                    ComplainantName = "Rajat Singh",
                    ComplainantAddressWard = "WARD 2",
                    ComplainantAddressHouseNo = "12",
                    ComplainantAddressHouseName = "Durga Niwas",
                    ComplainantAddressAreaInAddress = "Sadar",
                    ComplainantAddressZoneWardNo = "D3",
                    ComplainantAddressArea1 = "Sadar",
                    ComplainantAddressArea2 = "Sadar",
                    ComplainantAddressLandmark = "Samsung Showroom",
                    ComplainantAddressCity = "Howrah Municipal Corporation",
                    ComplainantAddressState = "West Bengal",
                    ComplainantAddressCountry = "India",
                    ComplainantAddressSTDCodeOfficeTelephone = "033",
                    ComplainantAddressOfficeTelephone = "6759603963",
                    ComplainantAddressSTDCodeResidenceTelephone = "033",
                    ComplainantAddressResidenceTelephone = "1550743536",
                    PhoneNumber = "5999771036",
                    Email = "rajatsingh@gmail.com",
                    PhotoUrl =
                        "https://res.cloudinary.com/sneha09/image/upload/v1682692665/cleain_eqbwwm.png",
                    ComplaintStatus = "Filed"
                },
                new Complaint
                {
                    ComplaintType = "SEWAGE",
                    ComplaintSubType = "REPAIRING",
                    DescriptionofComplaint =
                        "The sewage pipes are damaged from past 1 week and the dirty water is coming on roads and causing Diseases like Malaria",
                    ComplaintLocationHouseNo = "12",
                    ComplaintLocationHouseName = "Durga Niwas",
                    ComplaintLocationAreaInAddress = "Sadar",
                    ComplaintLocationZoneWardNo = "D3",
                    ComplaintLocationArea1 = "Sadar",
                    ComplaintLocationArea2 = "Sadar",
                    ComplaintLocationCity = "Durgapur Municipal Corporation",
                    ComplaintLocationPincode = "460001",
                    ComplainantName = "Ritik Pathak",
                    ComplainantAddressWard = "WARD 2",
                    ComplainantAddressHouseNo = "12",
                    ComplainantAddressHouseName = "Durga Niwas",
                    ComplainantAddressAreaInAddress = "Sadar",
                    ComplainantAddressZoneWardNo = "D3",
                    ComplainantAddressArea1 = "Sadar",
                    ComplainantAddressArea2 = "Sadar",
                    ComplainantAddressLandmark = "Samsung Showroom",
                    ComplainantAddressCity = "Durgapur Municipal Corporation",
                    ComplainantAddressState = "West Bengal",
                    ComplainantAddressCountry = "India",
                    ComplainantAddressSTDCodeOfficeTelephone = "033",
                    ComplainantAddressOfficeTelephone = "9953933514",
                    ComplainantAddressSTDCodeResidenceTelephone = "033",
                    ComplainantAddressResidenceTelephone = "2271599319",
                    PhoneNumber = "5977005479",
                    Email = "ritikpathak@gmail.com",
                    PhotoUrl =
                        "https://res.cloudinary.com/sneha09/image/upload/v1682692665/cleain_eqbwwm.png",
                    ComplaintStatus = "In Review"
                },
                new Complaint
                {
                    ComplaintType = "SEWAGE",
                    ComplaintSubType = "REPAIRING",
                    DescriptionofComplaint =
                        "The sewage pipes are damaged from past 1 week and the dirty water is coming on roads and causing Diseases like Malaria",
                    ComplaintLocationHouseNo = "12",
                    ComplaintLocationHouseName = "Durga Niwas",
                    ComplaintLocationAreaInAddress = "Sadar",
                    ComplaintLocationZoneWardNo = "D3",
                    ComplaintLocationArea1 = "Sadar",
                    ComplaintLocationArea2 = "Sadar",
                    ComplaintLocationCity = "South Delhi Municipal Corporation (SDMC)",
                    ComplaintLocationPincode = "460001",
                    ComplainantName = "Akansha Pandey",
                    ComplainantAddressWard = "WARD 2",
                    ComplainantAddressHouseNo = "12",
                    ComplainantAddressHouseName = "Durga Niwas",
                    ComplainantAddressAreaInAddress = "Sadar",
                    ComplainantAddressZoneWardNo = "D3",
                    ComplainantAddressArea1 = "Sadar",
                    ComplainantAddressArea2 = "Sadar",
                    ComplainantAddressLandmark = "Samsung Showroom",
                    ComplainantAddressCity = "South Delhi Municipal Corporation (SDMC)",
                    ComplainantAddressState = "New Delhi",
                    ComplainantAddressCountry = "India",
                    ComplainantAddressSTDCodeOfficeTelephone = "011",
                    ComplainantAddressOfficeTelephone = "0150201806",
                    ComplainantAddressSTDCodeResidenceTelephone = "011",
                    ComplainantAddressResidenceTelephone = "8706045852",
                    PhoneNumber = "6704036853",
                    Email = "akanshapandey@gmail.com",
                    PhotoUrl =
                        "https://res.cloudinary.com/sneha09/image/upload/v1682692665/cleain_eqbwwm.png",
                    ComplaintStatus = "In Review"
                },
                new Complaint
                {
                    ComplaintType = "SEWAGE",
                    ComplaintSubType = "REPAIRING",
                    DescriptionofComplaint =
                        "The sewage pipes are damaged from past 1 week and the dirty water is coming on roads and causing Diseases like Malaria",
                    ComplaintLocationHouseNo = "12",
                    ComplaintLocationHouseName = "Durga Niwas",
                    ComplaintLocationAreaInAddress = "Sadar",
                    ComplaintLocationZoneWardNo = "D3",
                    ComplaintLocationArea1 = "Sadar",
                    ComplaintLocationArea2 = "Sadar",
                    ComplaintLocationCity = "South Delhi Municipal Corporation (SDMC)",
                    ComplaintLocationPincode = "460001",
                    ComplainantName = "Aashima Singh",
                    ComplainantAddressWard = "WARD 2",
                    ComplainantAddressHouseNo = "12",
                    ComplainantAddressHouseName = "Durga Niwas",
                    ComplainantAddressAreaInAddress = "Sadar",
                    ComplainantAddressZoneWardNo = "D3",
                    ComplainantAddressArea1 = "Sadar",
                    ComplainantAddressArea2 = "Sadar",
                    ComplainantAddressLandmark = "Samsung Showroom",
                    ComplainantAddressCity = "South Delhi Municipal Corporation (SDMC)",
                    ComplainantAddressState = "New Delhi",
                    ComplainantAddressCountry = "India",
                    ComplainantAddressSTDCodeOfficeTelephone = "011",
                    ComplainantAddressOfficeTelephone = "9713702903",
                    ComplainantAddressSTDCodeResidenceTelephone = "011",
                    ComplainantAddressResidenceTelephone = "3000859654",
                    PhoneNumber = "0213244303",
                    Email = "ashimasingh@gmail.com",
                    PhotoUrl =
                        "https://res.cloudinary.com/sneha09/image/upload/v1682692665/cleain_eqbwwm.png",
                    ComplaintStatus = "Resolved"
                },
                new Complaint
                {
                    ComplaintType = "SEWAGE",
                    ComplaintSubType = "REPAIRING",
                    DescriptionofComplaint =
                        "The sewage pipes are damaged from past 1 week and the dirty water is coming on roads and causing Diseases like Malaria",
                    ComplaintLocationHouseNo = "12",
                    ComplaintLocationHouseName = "Durga Niwas",
                    ComplaintLocationAreaInAddress = "Sadar",
                    ComplaintLocationZoneWardNo = "D3",
                    ComplaintLocationArea1 = "Sadar",
                    ComplaintLocationArea2 = "Sadar",
                    ComplaintLocationCity = "North Delhi Municipal Corporation (NDMC)",
                    ComplaintLocationPincode = "460001",
                    ComplainantName = "Vikas Thapa",
                    ComplainantAddressWard = "WARD 2",
                    ComplainantAddressHouseNo = "12",
                    ComplainantAddressHouseName = "Durga Niwas",
                    ComplainantAddressAreaInAddress = "Sadar",
                    ComplainantAddressZoneWardNo = "D3",
                    ComplainantAddressArea1 = "Sadar",
                    ComplainantAddressArea2 = "Sadar",
                    ComplainantAddressLandmark = "Samsung Showroom",
                    ComplainantAddressCity = "North Delhi Municipal Corporation (NDMC)",
                    ComplainantAddressState = "New Delhi",
                    ComplainantAddressCountry = "India",
                    ComplainantAddressSTDCodeOfficeTelephone = "011",
                    ComplainantAddressOfficeTelephone = "1688040817",
                    ComplainantAddressSTDCodeResidenceTelephone = "011",
                    ComplainantAddressResidenceTelephone = "4985244573",
                    PhoneNumber = "7519787730",
                    Email = "vikasthapa@gmail.com",
                    PhotoUrl =
                        "https://res.cloudinary.com/sneha09/image/upload/v1682692665/cleain_eqbwwm.png",
                    ComplaintStatus = "Resolved"
                },
                new Complaint
                {
                    ComplaintType = "SEWAGE",
                    ComplaintSubType = "REPAIRING",
                    DescriptionofComplaint =
                        "The sewage pipes are damaged from past 1 week and the dirty water is coming on roads and causing Diseases like Malaria",
                    ComplaintLocationHouseNo = "12",
                    ComplaintLocationHouseName = "Durga Niwas",
                    ComplaintLocationAreaInAddress = "Sadar",
                    ComplaintLocationZoneWardNo = "D3",
                    ComplaintLocationArea1 = "Sadar",
                    ComplaintLocationArea2 = "Sadar",
                    ComplaintLocationCity = "East Delhi Municipal Corporation (EDMC)",
                    ComplaintLocationPincode = "460001",
                    ComplainantName = "Pranjal Agnihotri",
                    ComplainantAddressWard = "WARD 2",
                    ComplainantAddressHouseNo = "12",
                    ComplainantAddressHouseName = "Durga Niwas",
                    ComplainantAddressAreaInAddress = "Sadar",
                    ComplainantAddressZoneWardNo = "D3",
                    ComplainantAddressArea1 = "Sadar",
                    ComplainantAddressArea2 = "Sadar",
                    ComplainantAddressLandmark = "Samsung Showroom",
                    ComplainantAddressCity = "East Delhi Municipal Corporation (EDMC)",
                    ComplainantAddressState = "New Delhi",
                    ComplainantAddressCountry = "India",
                    ComplainantAddressSTDCodeOfficeTelephone = "011",
                    ComplainantAddressOfficeTelephone = "0520688890",
                    ComplainantAddressSTDCodeResidenceTelephone = "011",
                    ComplainantAddressResidenceTelephone = "4912361401",
                    PhoneNumber = "4042257013",
                    Email = "pranjalagnihotri@gmail.com",
                    PhotoUrl =
                        "https://res.cloudinary.com/sneha09/image/upload/v1682692665/cleain_eqbwwm.png",
                    ComplaintStatus = "Filed"
                },
                new Complaint
                {
                    ComplaintType = "SEWAGE",
                    ComplaintSubType = "REPAIRING",
                    DescriptionofComplaint =
                        "The sewage pipes are damaged from past 1 week and the dirty water is coming on roads and causing Diseases like Malaria",
                    ComplaintLocationHouseNo = "12",
                    ComplaintLocationHouseName = "Durga Niwas",
                    ComplaintLocationAreaInAddress = "Sadar",
                    ComplaintLocationZoneWardNo = "D3",
                    ComplaintLocationArea1 = "Sadar",
                    ComplaintLocationArea2 = "Sadar",
                    ComplaintLocationCity = "Nashik Municipal Corporation",
                    ComplaintLocationPincode = "460001",
                    ComplainantName = "Arun Gothi",
                    ComplainantAddressWard = "WARD 2",
                    ComplainantAddressHouseNo = "12",
                    ComplainantAddressHouseName = "Durga Niwas",
                    ComplainantAddressAreaInAddress = "Sadar",
                    ComplainantAddressZoneWardNo = "D3",
                    ComplainantAddressArea1 = "Sadar",
                    ComplainantAddressArea2 = "Sadar",
                    ComplainantAddressLandmark = "Samsung Showroom",
                    ComplainantAddressCity = "Nashik Municipal Corporation",
                    ComplainantAddressState = "Maharashtra",
                    ComplainantAddressCountry = "India",
                    ComplainantAddressSTDCodeOfficeTelephone = "020",
                    ComplainantAddressOfficeTelephone = "7686837966",
                    ComplainantAddressSTDCodeResidenceTelephone = "020",
                    ComplainantAddressResidenceTelephone = "1029742522",
                    PhoneNumber = "3554256522",
                    Email = "arungothi@gmail.com",
                    PhotoUrl =
                        "https://res.cloudinary.com/sneha09/image/upload/v1682692665/cleain_eqbwwm.png",
                    ComplaintStatus = "Filed"
                },
                new Complaint
                {
                    ComplaintType = "SEWAGE",
                    ComplaintSubType = "REPAIRING",
                    DescriptionofComplaint =
                        "The sewage pipes are damaged from past 1 week and the dirty water is coming on roads and causing Diseases like Malaria",
                    ComplaintLocationHouseNo = "12",
                    ComplaintLocationHouseName = "Durga Niwas",
                    ComplaintLocationAreaInAddress = "Sadar",
                    ComplaintLocationZoneWardNo = "D3",
                    ComplaintLocationArea1 = "Sadar",
                    ComplaintLocationArea2 = "Sadar",
                    ComplaintLocationCity = "Pimpri Chinchwad Municipal Corporation",
                    ComplaintLocationPincode = "460001",
                    ComplainantName = "Bhasker Lama",
                    ComplainantAddressWard = "WARD 2",
                    ComplainantAddressHouseNo = "12",
                    ComplainantAddressHouseName = "Durga Niwas",
                    ComplainantAddressAreaInAddress = "Sadar",
                    ComplainantAddressZoneWardNo = "D3",
                    ComplainantAddressArea1 = "Sadar",
                    ComplainantAddressArea2 = "Sadar",
                    ComplainantAddressLandmark = "Samsung Showroom",
                    ComplainantAddressCity = "Pimpri Chinchwad Municipal Corporation",
                    ComplainantAddressState = "Maharashtra",
                    ComplainantAddressCountry = "India",
                    ComplainantAddressSTDCodeOfficeTelephone = "020",
                    ComplainantAddressOfficeTelephone = "7815883249",
                    ComplainantAddressSTDCodeResidenceTelephone = "020",
                    ComplainantAddressResidenceTelephone = "1029211729",
                    PhoneNumber = "1154664708",
                    Email = "bhaskerlama@gmail.com",
                    PhotoUrl =
                        "https://res.cloudinary.com/sneha09/image/upload/v1682692665/cleain_eqbwwm.png",
                    ComplaintStatus = "Filed"
                },
                new Complaint
                {
                    ComplaintType = "SEWAGE",
                    ComplaintSubType = "REPAIRING",
                    DescriptionofComplaint =
                        "The sewage pipes are damaged from past 1 week and the dirty water is coming on roads and causing Diseases like Malaria",
                    ComplaintLocationHouseNo = "12",
                    ComplaintLocationHouseName = "Durga Niwas",
                    ComplaintLocationAreaInAddress = "Sadar",
                    ComplaintLocationZoneWardNo = "D3",
                    ComplaintLocationArea1 = "Sadar",
                    ComplaintLocationArea2 = "Sadar",
                    ComplaintLocationCity = "Thane Municipal Corporation",
                    ComplaintLocationPincode = "460001",
                    ComplainantName = "Vivek Lambachiya",
                    ComplainantAddressWard = "WARD 2",
                    ComplainantAddressHouseNo = "12",
                    ComplainantAddressHouseName = "Durga Niwas",
                    ComplainantAddressAreaInAddress = "Sadar",
                    ComplainantAddressZoneWardNo = "D3",
                    ComplainantAddressArea1 = "Sadar",
                    ComplainantAddressArea2 = "Sadar",
                    ComplainantAddressLandmark = "Samsung Showroom",
                    ComplainantAddressCity = "Thane Municipal Corporation",
                    ComplainantAddressState = "Maharashtra",
                    ComplainantAddressCountry = "India",
                    ComplainantAddressSTDCodeOfficeTelephone = "020",
                    ComplainantAddressOfficeTelephone = "6588063348",
                    ComplainantAddressSTDCodeResidenceTelephone = "020",
                    ComplainantAddressResidenceTelephone = "8757250406",
                    PhoneNumber = "0299754291",
                    Email = "viveklamba@gmail.com",
                    PhotoUrl =
                        "https://res.cloudinary.com/sneha09/image/upload/v1682692665/cleain_eqbwwm.png",
                    ComplaintStatus = "Filed"
                },
                new Complaint
                {
                    ComplaintType = "SEWAGE",
                    ComplaintSubType = "REPAIRING",
                    DescriptionofComplaint =
                        "The sewage pipes are damaged from past 1 week and the dirty water is coming on roads and causing Diseases like Malaria",
                    ComplaintLocationHouseNo = "12",
                    ComplaintLocationHouseName = "Durga Niwas",
                    ComplaintLocationAreaInAddress = "Sadar",
                    ComplaintLocationZoneWardNo = "D3",
                    ComplaintLocationArea1 = "Sadar",
                    ComplaintLocationArea2 = "Sadar",
                    ComplaintLocationCity = "Nagpur Municipal Corporation",
                    ComplaintLocationPincode = "460001",
                    ComplainantName = "Ananya Kapoor",
                    ComplainantAddressWard = "WARD 2",
                    ComplainantAddressHouseNo = "12",
                    ComplainantAddressHouseName = "Durga Niwas",
                    ComplainantAddressAreaInAddress = "Sadar",
                    ComplainantAddressZoneWardNo = "D3",
                    ComplainantAddressArea1 = "Sadar",
                    ComplainantAddressArea2 = "Sadar",
                    ComplainantAddressLandmark = "Samsung Showroom",
                    ComplainantAddressCity = "Nagpur Municipal Corporation",
                    ComplainantAddressState = "Maharashtra",
                    ComplainantAddressCountry = "India",
                    ComplainantAddressSTDCodeOfficeTelephone = "020",
                    ComplainantAddressOfficeTelephone = "6990227802",
                    ComplainantAddressSTDCodeResidenceTelephone = "020",
                    ComplainantAddressResidenceTelephone = "1015108878",
                    PhoneNumber = "5362592692",
                    Email = "ananyakapoor@gmail.com",
                    PhotoUrl =
                        "https://res.cloudinary.com/sneha09/image/upload/v1682692665/cleain_eqbwwm.png",
                    ComplaintStatus = "In Review"
                },
                new Complaint
                {
                    ComplaintType = "SEWAGE",
                    ComplaintSubType = "REPAIRING",
                    DescriptionofComplaint =
                        "The sewage pipes are damaged from past 1 week and the dirty water is coming on roads and causing Diseases like Malaria",
                    ComplaintLocationHouseNo = "12",
                    ComplaintLocationHouseName = "Durga Niwas",
                    ComplaintLocationAreaInAddress = "Sadar",
                    ComplaintLocationZoneWardNo = "D3",
                    ComplaintLocationArea1 = "Sadar",
                    ComplaintLocationArea2 = "Sadar",
                    ComplaintLocationCity = "East Delhi Municipal Corporation (EDMC)",
                    ComplaintLocationPincode = "460001",
                    ComplainantName = "Alisha Singh",
                    ComplainantAddressWard = "WARD 2",
                    ComplainantAddressHouseNo = "12",
                    ComplainantAddressHouseName = "Durga Niwas",
                    ComplainantAddressAreaInAddress = "Sadar",
                    ComplainantAddressZoneWardNo = "D3",
                    ComplainantAddressArea1 = "Sadar",
                    ComplainantAddressArea2 = "Sadar",
                    ComplainantAddressLandmark = "Samsung Showroom",
                    ComplainantAddressCity = "East Delhi Municipal Corporation (EDMC)",
                    ComplainantAddressState = "New Delhi",
                    ComplainantAddressCountry = "India",
                    ComplainantAddressSTDCodeOfficeTelephone = "011",
                    ComplainantAddressOfficeTelephone = "4814411051",
                    ComplainantAddressSTDCodeResidenceTelephone = "011",
                    ComplainantAddressResidenceTelephone = "0614359059",
                    PhoneNumber = "0078190068",
                    Email = "alishasingh@gmail.com",
                    PhotoUrl =
                        "https://res.cloudinary.com/sneha09/image/upload/v1682692665/cleain_eqbwwm.png",
                    ComplaintStatus = "Resolved"
                },
                new Complaint
                {
                    ComplaintType = "SEWAGE",
                    ComplaintSubType = "REPAIRING",
                    DescriptionofComplaint =
                        "The sewage pipes are damaged from past 1 week and the dirty water is coming on roads and causing Diseases like Malaria",
                    ComplaintLocationHouseNo = "12",
                    ComplaintLocationHouseName = "Devi Niwas",
                    ComplaintLocationAreaInAddress = "Sadar",
                    ComplaintLocationZoneWardNo = "D3",
                    ComplaintLocationArea1 = "Sadar",
                    ComplaintLocationArea2 = "Sadar",
                    ComplaintLocationCity = "DINDORI NAGAR PARISHAD / डिंडोरी नगर परिषद्",
                    ComplaintLocationPincode = "460001",
                    ComplainantName = "Neetanjali Tiwari",
                    ComplainantAddressWard = "WARD 2",
                    ComplainantAddressHouseNo = "12",
                    ComplainantAddressHouseName = "Devi  Niwas",
                    ComplainantAddressAreaInAddress = "Sadar",
                    ComplainantAddressZoneWardNo = "D3",
                    ComplainantAddressArea1 = "Sadar",
                    ComplainantAddressArea2 = "Sadar",
                    ComplainantAddressLandmark = "Samsung Showroom",
                    ComplainantAddressCity = "DINDORI NAGAR PARISHAD / डिंडोरी नगर परिषद्",
                    ComplainantAddressState = "Madhya Pradesh",
                    ComplainantAddressCountry = "India",
                    ComplainantAddressSTDCodeOfficeTelephone = "+07141",
                    ComplainantAddressOfficeTelephone = "5713693324",
                    ComplainantAddressSTDCodeResidenceTelephone = "07141",
                    ComplainantAddressResidenceTelephone = "6258545483",
                    PhoneNumber = "0716581876",
                    Email = "neetutiwari@gmail.com",
                    PhotoUrl =
                        "https://res.cloudinary.com/sneha09/image/upload/v1682692665/cleain_eqbwwm.png",
                    ComplaintStatus = "In Review"
                },
                new Complaint
                {
                    ComplaintType = "SEWAGE",
                    ComplaintSubType = "REPAIRING",
                    DescriptionofComplaint =
                        "The sewage pipes are damaged from past 1 week and the dirty water is coming on roads and causing Diseases like Malaria",
                    ComplaintLocationHouseNo = "12",
                    ComplaintLocationHouseName = "Sheela Niwas",
                    ComplaintLocationAreaInAddress = "Sadar",
                    ComplaintLocationZoneWardNo = "D3",
                    ComplaintLocationArea1 = "Sadar",
                    ComplaintLocationArea2 = "Sadar",
                    ComplaintLocationCity = "Pune Municipal Corporation",
                    ComplaintLocationPincode = "460001",
                    ComplainantName = "Rohini Bawne",
                    ComplainantAddressWard = "WARD 2",
                    ComplainantAddressHouseNo = "12",
                    ComplainantAddressHouseName = "Sheela Niwas",
                    ComplainantAddressAreaInAddress = "Sadar",
                    ComplainantAddressZoneWardNo = "D3",
                    ComplainantAddressArea1 = "Sadar",
                    ComplainantAddressArea2 = "Sadar",
                    ComplainantAddressLandmark = "Samsung Showroom",
                    ComplainantAddressCity = "Pune Municipal Corporation",
                    ComplainantAddressState = "Maharashtra",
                    ComplainantAddressCountry = "India",
                    ComplainantAddressSTDCodeOfficeTelephone = "020",
                    ComplainantAddressOfficeTelephone = "7539436664",
                    ComplainantAddressSTDCodeResidenceTelephone = "020",
                    ComplainantAddressResidenceTelephone = "1793172309",
                    PhoneNumber = "3509626475",
                    Email = "rohinibawne@gmail.com",
                    PhotoUrl =
                        "https://res.cloudinary.com/sneha09/image/upload/v1682692665/cleain_eqbwwm.png",
                    ComplaintStatus = "Filed"
                },
                new Complaint
                {
                    ComplaintType = "SEWAGE",
                    ComplaintSubType = "REPAIRING",
                    DescriptionofComplaint =
                        "The sewage pipes are damaged from past 1 week and the dirty water is coming on roads and causing Diseases like Malaria",
                    ComplaintLocationHouseNo = "12",
                    ComplaintLocationHouseName = " ",
                    ComplaintLocationAreaInAddress = "Sadar",
                    ComplaintLocationZoneWardNo = "D1",
                    ComplaintLocationArea1 = "Gokulpura",
                    ComplaintLocationArea2 = "Gokulpura",
                    ComplaintLocationCity = "Chennai Corporation",
                    ComplaintLocationPincode = "460001",
                    ComplainantName = "Aishwarya PG",
                    ComplainantAddressWard = "WARD 8",
                    ComplainantAddressHouseNo = "18",
                    ComplainantAddressHouseName = "Parihars",
                    ComplainantAddressAreaInAddress = "Gokulpura",
                    ComplainantAddressZoneWardNo = "D1",
                    ComplainantAddressArea1 = "Sadar",
                    ComplainantAddressArea2 = "Gokulpura",
                    ComplainantAddressLandmark = "Durga Mandir",
                    ComplainantAddressCity = "Chennai Corporation",
                    ComplainantAddressState = "Tamil Nadu",
                    ComplainantAddressCountry = "India",
                    ComplainantAddressSTDCodeOfficeTelephone = "044",
                    ComplainantAddressOfficeTelephone = "7382194591",
                    ComplainantAddressSTDCodeResidenceTelephone = "044",
                    ComplainantAddressResidenceTelephone = "9493191877",
                    PhoneNumber = "5745551985",
                    Email = "aishpg@gmail.com",
                    PhotoUrl =
                        "https://res.cloudinary.com/sneha09/image/upload/v1682692665/cleain_eqbwwm.png",
                    ComplaintStatus = "Filed"
                },
                new Complaint
                {
                    ComplaintType = "SEWAGE",
                    ComplaintSubType = "REPAIRING",
                    DescriptionofComplaint =
                        "The sewage pipes are damaged from past 1 week and the dirty water is coming on roads and causing Diseases like Malaria",
                    ComplaintLocationHouseNo = "12",
                    ComplaintLocationHouseName = "",
                    ComplaintLocationAreaInAddress = "Sadar",
                    ComplaintLocationZoneWardNo = "D1",
                    ComplaintLocationArea1 = "Hosapura",
                    ComplaintLocationArea2 = "Hosapura",
                    ComplaintLocationCity = "Thanjavur Corporation",
                    ComplaintLocationPincode = "460001",
                    ComplainantName = "Deblina Chatterjee",
                    ComplainantAddressWard = "WARD 8",
                    ComplainantAddressHouseNo = "18",
                    ComplainantAddressHouseName = "",
                    ComplainantAddressAreaInAddress = "Hosapura",
                    ComplainantAddressZoneWardNo = "D1",
                    ComplainantAddressArea1 = "Sadar",
                    ComplainantAddressArea2 = "Gokulpura",
                    ComplainantAddressLandmark = "Lal Mandir",
                    ComplainantAddressCity = "Thanjavur Corporation",
                    ComplainantAddressState = "Tamil Nadu",
                    ComplainantAddressCountry = "India",
                    ComplainantAddressSTDCodeOfficeTelephone = "044",
                    ComplainantAddressOfficeTelephone = "7382194591",
                    ComplainantAddressSTDCodeResidenceTelephone = "044",
                    ComplainantAddressResidenceTelephone = "9493191877",
                    PhoneNumber = "5745551985",
                    Email = "dabbuchat@gmail.com",
                    PhotoUrl =
                        "https://res.cloudinary.com/sneha09/image/upload/v1682692665/cleain_eqbwwm.png",
                    ComplaintStatus = "Filed"
                },
                new Complaint
                {
                    ComplaintType = "SEWAGE",
                    ComplaintSubType = "REPAIRING",
                    DescriptionofComplaint =
                        "The sewage pipes are damaged from past 1 week and the dirty water is coming on roads and causing Diseases like Malaria",
                    ComplaintLocationHouseNo = "12",
                    ComplaintLocationHouseName = "",
                    ComplaintLocationAreaInAddress = "JP nagar",
                    ComplaintLocationZoneWardNo = "D1",
                    ComplaintLocationArea1 = "Kawatipur",
                    ComplaintLocationArea2 = "Kawatipur",
                    ComplaintLocationCity = "Hosur City Municipal Corporation",
                    ComplaintLocationPincode = "460001",
                    ComplainantName = "Mohena PG",
                    ComplainantAddressWard = "WARD 8",
                    ComplainantAddressHouseNo = "18",
                    ComplainantAddressHouseName = "",
                    ComplainantAddressAreaInAddress = "Kawatipur",
                    ComplainantAddressZoneWardNo = "D1",
                    ComplainantAddressArea1 = "JP nagar",
                    ComplainantAddressArea2 = "Kawatipur",
                    ComplainantAddressLandmark = "Shiv Mandir",
                    ComplainantAddressCity = "Hosur City Municipal Corporation",
                    ComplainantAddressState = "Tamil Nadu",
                    ComplainantAddressCountry = "India",
                    ComplainantAddressSTDCodeOfficeTelephone = "044",
                    ComplainantAddressOfficeTelephone = "7382194591",
                    ComplainantAddressSTDCodeResidenceTelephone = "044",
                    ComplainantAddressResidenceTelephone = "9493191877",
                    PhoneNumber = "5745551985",
                    Email = "mohenab@gmail.com",
                    PhotoUrl =
                        "https://res.cloudinary.com/sneha09/image/upload/v1682692665/cleain_eqbwwm.png",
                    ComplaintStatus = "Filed"
                },
                new Complaint
                {
                    ComplaintType = "SEWAGE",
                    ComplaintSubType = "REPAIRING",
                    DescriptionofComplaint =
                        "The sewage pipes are damaged from past 1 week and the dirty water is coming on roads and causing Diseases like Malaria",
                    ComplaintLocationHouseNo = "12",
                    ComplaintLocationHouseName = "The Khans House",
                    ComplaintLocationAreaInAddress = "Sadar",
                    ComplaintLocationZoneWardNo = "D3",
                    ComplaintLocationArea1 = "Sadar",
                    ComplaintLocationArea2 = "Sadar",
                    ComplaintLocationCity = "Brihanmumbai Municipal Corporation",
                    ComplaintLocationPincode = "460001",
                    ComplainantName = "Aisha Khan",
                    ComplainantAddressWard = "WARD 2",
                    ComplainantAddressHouseNo = "12",
                    ComplainantAddressHouseName = "The Khans House",
                    ComplainantAddressAreaInAddress = "Sadar",
                    ComplainantAddressZoneWardNo = "D3",
                    ComplainantAddressArea1 = "Sadar",
                    ComplainantAddressArea2 = "Sadar",
                    ComplainantAddressLandmark = "Samsung Showroom",
                    ComplainantAddressCity = "Brihanmumbai Municipal Corporation",
                    ComplainantAddressState = "Maharashtra",
                    ComplainantAddressCountry = "India",
                    ComplainantAddressSTDCodeOfficeTelephone = "020",
                    ComplainantAddressOfficeTelephone = "6183375964",
                    ComplainantAddressSTDCodeResidenceTelephone = "020",
                    ComplainantAddressResidenceTelephone = "6997497349",
                    PhoneNumber = "8635336207 ",
                    Email = "aishakhan@gmail.com",
                    PhotoUrl =
                        "https://res.cloudinary.com/sneha09/image/upload/v1682692665/cleain_eqbwwm.png",
                    ComplaintStatus = "Resolved"
                },
            };

            await context.Complaints.AddRangeAsync(complaints);
            await context.SaveChangesAsync();
        }
    }
}
